
services:
  app:
    build: # this is only when i need to rebuild it. comment out when not needed
      context: .
      dockerfile: Dockerfile.build_and_run
    image: quizmaster:localv2
    stdin_open: true
    tty: true
    ports: ["8080:9000"] # outer port : inner port (can't be changed)
    volumes:
      - ./conf/quiz:/app/conf/quiz
      - ./conf/application.conf:/app/conf/application.conf
    command: "bin/server"
