title: Демонстрационная викторина
author: Jens Nyman
instructionsOnFirstSlide: Пожалуйста, не ищите ответы в интернете
masterSecret: quiz
language: ru

usageStatistics:
    sendAnonymousUsageDataAtEndOfQuiz: true

defaults:
  maxTimeSeconds: 120
  pointsToGain: 1
  multipleAnswers_pointsToGainPerAnswer: 1
  multipleQuestions_pointsToGainPerQuestion: 1
  orderItems_pointsToGainInTotal: 2

rounds:
  - name: География
    image: https://freesvg.org/img/globe-310324.png
    questions:
      - question: В честь кого названа страна Колумбия?
        answer: Христофор Колумб

      - question: Какова столица Бельгии?
        choices: [Париж, Лондон, Брюссель, Берлин]
        answer: Брюссель
        pointsToGain: 1
        pointsToGainOnFirstAnswer: 2

      - question: Какова столица Франции?
        choices: [Париж, Лондон, Брюссель, Берлин]
        answer: Париж
        image: https://raw.githubusercontent.com/nymanjens/quizmaster/master/conf/quiz/assets/geography/france.png
        answerImage: geography/france-answer.png
        answerDetail: |
          Изображение распространяется по лицензии Creative Commons от Destination2
          (www.destination2.co.uk)
        pointsToGain: 0
        maxTimeSeconds: 120

      - question: Какой город показан в этом видео 1935 года?
        answer: Гватемала-Сити
        video: geography/about_bananas.mp4
        onlyFirstGainsPoints: true
        showSingleAnswerButtonToTeams: true

      - questionType: orderItems
        question: Расположите эти города от меньшего к большему
        questionDetail: Население по данным Google на июль 2020
        masterNotes: Уточните, что это не вопрос с подвохом
        image: {src: geography/globe.png, size: small}
        orderedItemsThatWillBePresentedInAlphabeticalOrder:
         - {item: Рига, answerDetail: ~600 тыс.}
         - {item: Стокгольм, answerDetail: ~1 млн}
         - {item: Берлин, answerDetail: ~4 млн}
         - {item: Лондон, answerDetail: ~9 млн}
        pointsToGain: 3


  - name: Музыкальный раунд
    image: https://upload.wikimedia.org/wikipedia/commons/f/f6/Music_1_-_The_Noun_Project.svg
    questions:
      - question: В честь какого времени года названа эта композиция?
        questionDetail: (Музыка без роялти от Bensound)
        answer: Лето

      - questionType: multipleAnswers
        question: Назовите участников группы Metallica
        questionDetail: (на 2021 год)
        answers:
          - {answer: Джеймс Хэтфилд, answerDetail: Ведущий вокалист}
          - Ларс Ульрих
          - Кирк Хэмметт
          - Роберт Трухильо
        answersHaveToBeInSameOrder: false
        image: https://upload.wikimedia.org/wikipedia/commons/9/9e/Metallica_-_2003.jpg
        pointsToGainPerAnswer: 1

      - questionType: multipleQuestions
        questionTitle: Сможете ли вы узнать песню по тексту?
        questionDetail: |
          With the lights out, it's less dangerous
          Here we are now, entertain us
        questions:
          - {question: "Как называется песня?", answer: "Smells Like Teen Spirit", answerDetail: 1991}
          - {question: "Какой исполнитель?", answer: Nirvana}
          - {question: "В каком году вышла песня?", answer: 1991, pointsToGain: 2}
        image: https://cdn.pixabay.com/photo/2016/01/12/17/20/sheet-music-1136234_960_720.png
